config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # root "pages#home", page: "home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/how_to_play', to: 'pages#how_to', as: :how_to_play
  get 'pages/dashboard', to: 'pages#dashboard', as: :dashboard
  resources :games, only: %i[create] do
    resources :rounds, only: %i[create]
  end

  get 'games/:id/score', to: 'games#score', as: :game_score
  get 'games/:id/game', to: 'games#game', as: :game
  get 'games/:id/mcq', to: 'games#mcq', as: :mcq
  get 'games/:id/mcq_score', to: 'games#mcq_score', as: :mcq_score
  get 'games/:id/slide', to: 'games#slide', as: :slide
  get 'games/:id/show_slide_score', to: 'games#show_slide_score', as: :show_slide_score
  post 'games/:id/score_slide_game', to: 'games#score_slide_game', as: :score_slide_game
end

app/views/pages/dashboard.html.erb
<div class="dash-container">
  <div class="dash-header">
    <div class="dash-back-btn">
      <%= link_to "", root_path, class: 'dash-back-btn-icon' %>
    </div>
    <p class = "invisible"><% current_user.nil? ? "Not Logged In" : current_user.username.capitalize %></p>
    <p class = "dash-title"> Game history </p>
    <div class="dash-header-placeholder"></div>
  </div>
  <div class="dash-inner-container">
    <div>
     <!--  <div class="dash-headline-container ">
        <div class="dash-logo"></div>
        <div class="dash-headline">Dashboard</div>
      </div> -->
    </div>

    <div class="dash-username">
    <% display_name = "" %>
    <% if current_user.nil? %>
      <% display_name = "<em>You aren't logged in!</em" %>
    <% elsif current_user.username.nil?%>
      <% display_name = current_user.email  %>
    <% else %>
      <% display_name = current_user.username %>
    <% end %>
    <% %>
    <p><%= display_name %></p>
    </div>



    <div class="dash-text">

      <div class="d-flex justify-content-center">
        <div class="d-flex dash-profile-container">
          <div class="justify-content-between">
           <div class = "dash-stats number" > <%= current_user.games.count %> </div>
           <p class= "dash-stats title">Games</p>
         </div>
          <div class="justify-content-between">
            <div class= "dash-stats number" > <%= @rounds.count %> </div>
            <p class= "dash-stats title">Questions</p>
          </div>
          <div class="justify-content-between">
            <!-- TO DO: Update this line to getpoints total -->
            <div class= "dash-stats number" >
            <% score = 0 %>
             <% current_user.games.each do |game| %>
              <% score += game.score %>
              <% end %>
              <%= score %>
           </div>
            <p class= "dash-stats title">Points</p>
          </div>
       </div>
     </div>


       <!-- Games 'gallery'  -->
      <div class="dash-games-container">
        <% if @games[0].nil? %>
          <div class="container d-flex align-items-center justify-content-center h-100">
            <p>no games played yet</p>
          </div>
        <% else %>
          <!-- Loop through all games -->
          <% @games.each do |game| %>

            <!-- Case: How to display MCQ -->
            <% if game.game_mode == "MCQ" %>
              <div class="dash-pill-holder">
                <a class="pill dash-pill d-flex" href="/games/<%= game.id %>/mcq_score">
                  <div class= "dash-date" > <%= game.created_at.day %>\<%= game.created_at.month %>\<%= game.created_at.year %> </div>
                  <div class= "dash-game-mode" > MCQ </div>
                  <div class="shevron-right"> </div>
                </a>
                <% if game.score > 0 %>
                  <div class = "badge">+<%= game.score %></div>
                <% else %>
                  <div class = "badge" style="visibility: hidden;"></div>
                <% end %>
              </div>

            <!-- Case: How to display Tryout -->
            <% elsif game.game_mode == "Try Out" %>
              <div class="dash-pill-holder">
                <a class="pill dash-pill d-flex" href="/games/<%= game.id %>/game">
                  <div class= "dash-date" > <%= game.created_at.day %>\<%= game.created_at.month %>\<%= game.created_at.year %> </div>
                  <div class= "dash-game-mode" > Quickplay </div>
                  <div class="shevron-right"> </div>
                </a>
                <% if game.score > 0 %>
                  <div class = "badge">+<%= game.score %></div>
                <% else %>
                  <div class = "badge" style="visibility: hidden;"></div>
                <% end %>
              </div>

            <!-- Case: How to display "Sortable" -->
            <% else %>
              <div class="dash-pill-holder">
                <% if game.score > 0 %>
                  <div class = "badge">+<%= game.score %></div>
                <% else %>
                  <div class = "badge" style="visibility: hidden;"></div>
                <% end %>
                <a class="pill dash-pill d-flex" href="/games/<%= game.id %>/game">
                  <div class= "dash-date" > <%= game.created_at.day %>\<%= game.created_at.month %>\<%= game.created_at.year %> </div>
                  <div class= "dash-game-mode" > Sortable </div>
                  <div class="shevron-right"> </div>
                </a>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script>
  let my_body = document.querySelector('body')
  const changeBodyBackgroundColor = () => {
    my_body.style.background = '#F8F9FA'
  }
  changeBodyBackgroundColor();
</script>

app/views/pages/home.html.erb
<div id="delayRedirect fadeable">
  <% if session[:first_visit] %>
    <div class="splash-container fadeable" id="splash-container fadeable">
      <div class="splash-logo fadeable"></div>
      <div class="ball1 fadeable"></div>
      <div class="ball2 fadeable"></div>
      <div class="ball3 fadeable"></div>
    </div>
    <% session[:first_visit] = false %>
  <% end %>
</div>

<div class="pillbox_outer">
  <div class="pillbox_inner">
    <div class="menu-headline-container">
      <div class="menu-logo" style="background-image"></div>
      <div class="menu-how-to-play-link">
        <a href="/pages/how_to_play" class="menu-htp-link">
          <div class="menu-how-to-play-link-icon">
            <%= image_tag("game_options_menu_symbol.png", id: 'game-options-menu-symbol')%>
          </div>
          <div class="menu-how-to-play-link-text">How to play</div>
        </a>
      </div>

    </div>
    <div class="pillbox-add-top-margin-main-page ">

      <% if user_signed_in? %>
      <%= button_to "Try Out", games_path, params: {game: {game_mode: "Try Out"}}, class: 'pill mb-0 d-flex justify-content-center' %>
      <%= button_to "5 Rounds", games_path, params: {game: {game_mode: "MCQ"}}, class: 'pill mb-0 d-flex justify-content-center' %>
      <%= button_to "Sortable", games_path, params: {game: {game_mode: "Sortable"}}, class: 'pill mb-0 d-flex justify-content-center' %>
      <div class="pill mb-0 d-flex justify-content-center">Multiplayer (Coming soon)</div>
      <% else %>
      <%= button_to "Try Out", games_path, params: {game: {game_mode: "Try Out"}}, class: 'pill mb-0 d-flex justify-content-center' %>
      <% end %>
    </div>
    <div class = "user-buttons">
      <% if user_signed_in? %>
      <%= link_to "", destroy_user_session_path, method: :delete, class: 'logout-icon text-dark mb-0 d-flex justify-content-center' %>
      <div class="username-container">
        <div class="username-displayed d-flex">
        <i class="fas fa-user"></i>  <%= current_user.username %>
        </div>
      </div>
       <%= link_to "", dashboard_path, class: 'my-stats-icon text-dark mb-0 d-flex justify-content-center' %>
       <% else %>
       <div class = "user-buttons-signed-out">
       <%= link_to "Login", user_session_path, class: 'mb-0 d-flex justify-content-center sign-in-pill' %>
       <%= link_to "or Sign up", new_user_registration_path, class: 'mb-0 d-flex justify-content-center sign-up-menu-button' %>
       </div>
       <% end %>
      </div>
    </div>
  </div>



<script>

  // Script to during the make the Body element grey
  let my_body = document.querySelector('body')
  const changeBodyBackgroundColor = () => {
    my_body.style.background = '#545252'
  }
  changeBodyBackgroundColor();

  // Script to handle delay, switching from Splash screen to Menu screen
  const slowfadeElement = (element) => {
    element.classList.add("slow-fade");
  };

  const fadeables = document.querySelectorAll('.fadeable');

  const fadeAfterDelay = (elements) => {
    elements.forEach((element) => {
      setTimeout(() => slowfadeElement(element), 4000);
    });
  };

  const removeAfterDelay = (elements) => {
    elements.forEach((element) => {
      setTimeout(() => element.remove(), 6000);
    });
  };

  fadeAfterDelay(fadeables);
  removeAfterDelay(fadeables);

</script>

app/views/pages/how_to.html.erb
<div class = "htp-container how-to-container">

  <div class = "htp-inner-container">
    <div>
      <div class = "htp-headline-container ">
        <%= image_tag("game_options_menu_symbol.png", class: "htp-headline-icon") %>
        <div class="htp-headline">  How to play</div>
      </div>
    </div>

    <div class="htp-options htp-text">
      <p>Partly is a search-engine autocomplete based quiz</p>
      <%= image_tag("how_to_play.png", class: 'htp-pic')%>
      <p>Every question is a search query in th search-bar. <br> The player has to guess which phrase is the first in the list of suggestions by auto complete. <br> You get 4 Answers to pick from. Good Luck!</p>
    </div>
    <a href="/">
    <div class="pill htp-pill">OK, got it!</div>
    </a>

  </div>

</div>


<script>
  let my_body = document.querySelector('body')
  const changeBodyBackgroundColor = () => {
    my_body.style.background = '#545252'
  }
  changeBodyBackgroundColor();
</script>