config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # root "pages#home", page: "home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/how_to_play', to: 'pages#how_to', as: :how_to_play
  get 'pages/dashboard', to: 'pages#dashboard', as: :dashboard
  resources :games, only: %i[create] do
    resources :rounds, only: %i[create]
  end

  get 'games/:id/score', to: 'games#score', as: :game_score
  get 'games/:id/game', to: 'games#game', as: :game
  get 'games/:id/mcq', to: 'games#mcq', as: :mcq
  get 'games/:id/mcq_score', to: 'games#mcq_score', as: :mcq_score
  get 'games/:id/slide', to: 'games#slide', as: :slide
  get 'games/:id/show_slide_score', to: 'games#show_slide_score', as: :show_slide_score
  post 'games/:id/score_slide_game', to: 'games#score_slide_game', as: :score_slide_game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :rounds, dependent: :destroy
  validates :game_mode, inclusion: { in: ["Try Out","MCQ","Sortable"]}
  validates :score, presence: true, numericality: { only_integer: true}
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, if: :tryout_game?

  before_action :set_game, only: [:score, :game, :mcq, :mcq_score, :slide, :score_slide_game, :show_slide_score ]

  def create
     # creates a game with our tryout user and redirects to our game html
     @game = Game.new(game_params)
     authorize @game
    # no user yet (try out)
    if @game.game_mode == "Try Out"
      if user_signed_in?
        @game.user = current_user
      else
        @game.user = User.find_by(email: 'tryout_guy@partly.com')
      end
      @game.save!
      redirect_to game_path(@game)
    elsif @game.game_mode == "MCQ"
      @game.user = current_user
      @game.save!
      redirect_to mcq_path(@game)
    elsif @game.game_mode == "Sortable"
      @game.user = current_user
      @game.save!
      redirect_to slide_path(@game)
    end
  end

  def game
    # looks for rounds with our game id
    @rounds = Round.where(game_id: @game.id)
    # if no round exists it will start a with a random question and the 4 possible answers but randomized
    #check if there are rounds
    if @rounds[0].nil?
      @question = rand_quest
      @answers = Answer.where(question_id: @question.id).shuffle
      session[:round_ordered_answers] = @answers
      # if round exists (question already answered) render the page with the answered question and the answers in the right order
    else
      if @rounds[0].answer.rank == 1
        @game.update(score: 1)
      end
      @question = Question.find(@rounds.last.question_id)
      @answers = []
      session[:round_ordered_answers].each do |answer_data|
      @answers << Answer.new(answer_data)
      end
    end
  end

  def mcq
    # looks for rounds with our game id
    @rounds = Round.where(game_id: @game.id)

    # if no round exists it will start a with a random question and the 4 possible answers but randomized
    #check if there aree rounds
    if @rounds[0].nil? || @rounds.count < 5
      @question = rand_quest
      @answers = Answer.where(question_id: @question.id).shuffle
    else
      redirect_to mcq_score_path(@game)
    end
  end

  def mcq_score
    @rounds = Round.where(game_id: @game.id)
    game_score = 0;
    @rounds.each do |round|
      if round.answer.rank == 1
        game_score += 1
      end
    end
    @game.update(score: game_score)
  end

  def slide
    @rounds = Round.where(game_id: @game.id)
    if @rounds[0].nil?
      @question = rand_quest
      @answers = Answer.where(question_id: @question.id).shuffle
      session[:round_ordered_answers] = @answers
    elsif @rounds.count == 3
      redirect_to slide_score_path(@game) #placeholder for now
    else
      @question = Question.find(@rounds.last.question_id)
      @answers = []
      session[:round_ordered_answers].each do |answer_data|
        @answers << Answer.new(answer_data)
      end
    end
  end

  def score_slide_game
    sorted_answers = []
    sorted_answers << Answer.find(params[:answer_1])
    sorted_answers << Answer.find(params[:answer_2])
    sorted_answers << Answer.find(params[:answer_3])
    sorted_answers << Answer.find(params[:answer_4])

    session[:sorted_answers] = sorted_answers
    game_score = 0
    sorted_answers.each_with_index do |answer, indx|
      if answer.rank == indx + 1
          game_score += 1
      end
    end
    @game.update(score: game_score)
    redirect_to show_slide_score_path(@game)
  end

  def show_slide_score
    @answers = session[:sorted_answers]
    @answers = @answers.map do |answer_data|
      answer_data = Answer.new(answer_data)
    end
    @question = @answers[0].question
  end

  private

  def set_game
    @game = Game.find(params[:id])
    authorize @game
  end

  def game_params
    params.require(:game).permit(:game_mode)
  end

  # get random question
  def rand_quest
    # Get initial question
    count = Question.count
    random_offset = rand(count)
    random_quest = Question.offset(random_offset).first

    # Initialize storage for recent questions if not yet initialized
    if session[:recent_questions].nil?
      session[:recent_questions] = []
    end

    # Keep on getting questions until we find a 'new' one
    while session[:recent_questions].include?(random_quest.id)
      count = Question.count
      random_offset = rand(count)
      random_quest = Question.offset(random_offset).first
    end

    # Update list of old questions
    session[:recent_questions] << random_quest.id
    if session[:recent_questions].count > 30
      session[:recent_questions].shift
    end
    return random_quest
  end

  def tryout_game?
  # 1. we are about to create a new game, with a mode of 'Try Out'
    if params[:action] == 'create'
      return true if params[:game][:game_mode] == 'Try Out'
    else
      # 2. there is already a game, which has a mode of 'Try Out'
      game = Game.find(params[:id])
      return !game.nil? && game.game_mode == 'Try Out'
    end
  end
end

app/views/games/game.html.erb
<div class="pillbox_outer bg-light">
  <div class="game_inner bg-light">
    <div>
      <a href="/">
      <div class="logo-40-px" style="background-image"></div>
      </a>
    </div>
    <div class="pillbox-add-top-margin">
     <div class="pill-question pill-align-left icon search"><%= @question.content %></div>
      <div class="pill hidden">spacer</div>
      <!-- Set color order, and position counter, for us in render loops -->
      <% color_order = ['red', 'green', 'blue', 'yellow'] %>
      <% position_counter = 0 %>

      <!-- If game isn't done yet, get a new answer from the user. -->
      <% if @rounds.last.nil? || @game.game_mode == "MCQ" && @game.rounds.count < 5 %>
        <% @answers.each do |answer| %>
          <%= button_to answer.content,
                        game_rounds_path(@game),
                        params: {round: {duration: 30,
                                         question_id: @question.id,
                                         answer_id: answer.id }},
                        class: "shown-option pill pill-align-right-btn pill-#{color_order[position_counter]} mb-0 d-flex",
                        id: "option-#{position_counter}"%>
          <%  position_counter += 1 %>
          <% end %>

       <!-- If we're done with one round, and the mode is 'Try Out', show the tryout score screen. -->
       <% elsif  @game.game_mode == "Try Out" %>
          <% @answers.each do |answer| %>

            <!-- Rendering a correct, chosen result with a light blue border and a checkmark -->
            <% if answer.rank == 1 && answer.id == @rounds.last.answer.id%>
               <div class="pill pill-tryout-result d-flex align-items-center px-4 justify-content-between pill-<%=color_order[position_counter]%> "
                    id="result-<%= position_counter + 1 %>"
                    data-answer-rank="<%= answer.rank %>"
                    ><i class="fas fa-check mb-0"></i><%= answer.content %>
               </div>

             <!-- Rendering a correct, not-chosen result with a checkmark -->
             <% elsif answer.rank == 1 %>
               <div class="pill pill-tryout-result d-flex align-items-center px-4 justify-content-between pill-<%=color_order[position_counter]%> "
                    id="result-<%= position_counter + 1 %>"
                    data-answer-rank="<%= answer.rank %>"
                    ><i class="fas fa-check mb-0"></i><%= answer.content %>
               </div>

            <!-- Rendering a wrong, chosen result with an 'X', a light blue border, and a white overlay -->
            <% elsif answer.id == @rounds.last.answer.id %>
                <div class="pill pill-tryout-result pill-translucent-overlay d-flex align-items-center justify-content-between px-4 pill-<%=color_order[position_counter]%>"
                     id="result-<%= position_counter + 1 %>"
                     data-answer-rank="<%= answer.rank %>"
                     ><i class="fas fa-times"></i><%= answer.content %>
                </div>

            <!-- Render all non chosen, non-right answer w/ a white overlay -->
            <% else %>
                <div class="pill pill-tryout-result pill-translucent-overlay justify-content-end px-4 pill-<%=color_order[position_counter]%> d-flex"
                     id="result-<%= position_counter + 1 %>"
                     data-answer-rank="<%= answer.rank %>"
                     ><%= answer.content %>
                </div>
            <% end %>
            <%  position_counter += 1 %>

            <!-- Close the div! -->
          <% end # end loop: render options %>
          <div class="pill hidden">spacer</div>

          <%= button_to "Play again", games_path, class: 'pill mb-0 d-flex justify-content-center' , params: {game: {game_mode: @game.game_mode}}%>
          <%= link_to "Back to Menu", root_path, class: 'pill last-button d-flex justify-content-center' %>
      <% end %>
    </div>
   </div>
  </div>
<script>

  // Script to during the make the Body element grey
  let myBody = document.querySelector('body');
  const changeBodyBackgroundColor = () => {
    myBody.style.background = '#F8F9FA';
  }
  changeBodyBackgroundColor();


</script>

app/views/games/mcq.html.erb
<div class="pillbox_outer bg-light">
  <div class="mcq-inner bg-light">
    <div>
      <a href="/">
      <div class="logo-40-px" style="background-image"></div>
      </a>
    </div>
    <div class="pillbox-add-top-margin ">
      <div class="pill-question pill-align-left icon search"><%= @question.content %></div>
      <div class="pill hidden">spacer</div>

      <!-- Set color order, and position counter, for us in render loops -->
      <% color_order = ['#E8453C', '#3AA757', '#4688F1', '#FABB2D'] %>
      <% position_counter = 0 %>

      <!-- If game isn't done yet, get a new answer from the user. -->
      <% if  @game.rounds.count < 5 %>
        <% @answers.each do |answer| %>

          <!-- YANIV CHANGED BUTTON_TO => LINK_TO (MUST HANDLE ANSWER SUBMISSION) -->
          <%= button_to answer.content,
                        game_rounds_path(@game),
                        params: {'round' => {'duration' =>  30,
                                         'question_id' =>  @question.id,
                                         'answer_id' =>  answer.id }},
                        class: "mcq-answer shown-option pill pill-align-right-btn pill-#{color_order[position_counter]} mb-0 d-flex",
                        id: "option-#{position_counter}",
                        style: "background-color: #{color_order[position_counter]}"%>
          <%  position_counter += 1 %>
        <% end %>
      <% end %>
      <div class="pill hidden">spacer</div>

      <%= link_to "Back to Menu", root_path, class: 'pill mb-0 d-flex justify-content-center' %>

      <div class="round-count">
      <h4><%= @rounds.count + 1 %> | 5</h4>
      </div>
    </div>
  </div>



  <script>

  // Script to during the make the Body element grey
  let myBody = document.querySelector('body');
  const changeBodyBackgroundColor = () => {
    myBody.style.background = '#F8F9FA';
  }
  changeBodyBackgroundColor();



  </script>

app/views/games/mcq_score.html.erb
<div class="pillbox_outer bg-light">
  <div class="mcqs-inner bg-light">
    <div>
      <a href="/">
      <div class="logo-40-px" style="background-image"></div>
      </a>
    </div>
    <div>
      <div class="pill hidden">spacer</div>
      <% sum = 0 %>
      <% @rounds.each do |round|%>
      <% if round.answer.rank == 1 %>

          <div class="pill pill-tryout-result d-flex align-items-center px-4 justify-content-between pill-green">
            <i class="fas fa-check mb-0"></i>
            <%= round.answer.content %>
          </div>

          <% sum += 1 %>
      <% else %>

        <div class="pill-result pill-tryout-result d-flex align-items-center px-4 justify-content-between pill-red">
          <i class="fas fa-times mb-0"></i>
          <%= round.answer.content %>
        </div>
      <% end %>
    <% end %>
    <div class="d-flex justify-content-center">
      <% if sum < 1 %>
      <i class="fas fa-sad-tear smiley-backo"></i>
      <% elsif sum < 2 %>
      <i class="fas fa-frown smiley-backo"></i>
      <% elsif sum < 3 %>
      <i class="fas fa-meh smiley-backo"></i>
      <% elsif sum < 4 %>
      <i class="fas fa-smile smiley-backo"></i>
      <% else %>
      <i class="fas fa-laugh-wink smiley-backo"></i>
      <% end %>
    </div>
      <%= link_to "Back to Menu", root_path, class: 'pill mb-0 d-flex justify-content-center' %>
      <%= button_to "Play again", games_path, class: 'pill last-button d-flex justify-content-center' , params: {game: {game_mode: @game.game_mode}}%>
    </div>
  </div>

<script>

  // Script to during the make the Body element grey
  let myBody = document.querySelector('body');
  const changeBodyBackgroundColor = () => {
    myBody.style.background = '#F8F9FA';
  }
  changeBodyBackgroundColor();

</script>

app/views/games/score.html.erb
<h1>Games#score</h1>
<p>Find me in app/views/games/score.html.erb</p>
<%= link_to "back to Home?", root_path %>

app/views/games/show_slide_score.html.erb
<div class="pillbox_outer_slide back-opac">
  <div class="game_inner_slide">
    <div>
      <a href="/">
        <div class="logo-40-px" style="background-image"></div>
      </a>
    </div>
    <div class="pillbox-add-top-margin ">
      <div class="pill-question pill-align-left icon search"><%= @question.content %></div>
      <div class="pill hidden">spacer</div>


      <div class="set-width">
        <div class="go_back">
          <% color_order = ['red', 'green', 'blue', 'yellow'] %>


          <div class="pill-outer">
            <h2 class="font-weight-bold" style="color: <%= @answers[0].rank == 1 ? "#3BA758" : "#E8463C" %>;">
              1
            </h2>
          </div>

          <div class="pill-outer">
            <h2 class="font-weight-bold" style="color: <%= @answers[1].rank == 2 ? "#3BA758" : "#E8463C" %>;">
              2
            </h2>
          </div>

          <div class="pill-outer">
            <h2 class="font-weight-bold" style="color: <%= @answers[2].rank == 3 ? "#3BA758" : "#E8463C" %>;">
              3
            </h2>
          </div>

          <div class="pill-outer">
            <h2 class="font-weight-bold" style="color: <%= @answers[3].rank == 4 ? "#3BA758" : "#E8463C" %>;">
              4
            </h2>
          </div>



        </div>


        <ul class="container-slide-score slide-result-list">

          <!-- Initialize counter to cycle through colors   -->
          <% color_order = ['red', 'green', 'blue', 'yellow'] %>
          <% position_counter = 0 %>

          <!-- Loop through answers, rendering each element w/ the relevant id -->
          <% @answers.each_with_index do |answer, index| %>
          <% my_class =  "pill-slide-score pill-align-sortable"%>
          <% if answer.rank == index + 1 %>

          <li class="<%= my_class %> pill-green" data-answer-number="<%= answer.id %>">
            <i class="fas fa-check"></i>
            <%= answer.content %>
          </li>
          <% else %>
          <li class="<%= my_class %> pill-red" data-answer-number="<%= answer.id %>">
            <i class="fas fa-times d-flex align-items-center"><p class="real-rank">( <%= answer.rank %> )</p></i>


            <%= answer.content %>
          </li>
          <% end %>

          <% position_counter += 1 %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="slide-score-buttons">
  <%= link_to "Back to Menu", root_path, class: 'pill mb-0 d-flex justify-content-center' %>
  <%= button_to "Play again", games_path, class: 'pill last-button d-flex justify-content-center' , params: {game: {game_mode: @game.game_mode}}%>

</div>

app/views/games/slide.html.erb
<div class="pillbox_outer_slide back-opac">
  <div class="game_inner_slide">
    <div>
      <a href="/">
        <div class="logo-40-px" style="background-image"></div>
      </a>
    </div>
    <div class="pillbox-add-top-margin ">
      <div class="pill-question pill-align-left icon search"><%= @question.content %></div>
      <div class="pill hidden">spacer</div>

      <% if @rounds.last.nil?  %>

        <div class="set-width">

          <div class="go_back">
            <div class="pill-outer">
              <h2>1</h2>
            </div>

            <div class="pill-outer">
              <h2>2</h2>
            </div>

            <div class="pill-outer">
              <h2>3</h2>
            </div>

            <div class="pill-outer">
              <h2>4</h2>
            </div>
          </div>


          <ul id="quest-sort" class="container-slide-score slide-result-list">
            <!-- Initialize counter to cycle through colors   -->
            <% color_order = ['red', 'green', 'blue', 'yellow'] %>
            <% position_counter = 0 %>
            <!-- Loop through answers, rendering each element w/ the relevant id -->
            <% @answers.each_with_index do |answer, index| %>
            <% my_class =  "sort-option pill-slide-score pill-align-sortable pill-#{color_order[position_counter]}"%>
            <li class="<%= my_class %>" data-answer-number="<%= answer.id %>">
              <i class="fas fa-bars"></i>
              <%= answer.content %>
            </li>
            <% position_counter += 1 %>
            <% end %>
          </ul>

        </div>

      <% end %>

    </div>
  </div>

<div class = "slide-reveal-button justify-content-center">
  <%= form_tag score_slide_game_path(@game) do %>
  <% @answers.each_with_index do |answer, index| %>
  <%= hidden_field_tag "answer_#{index + 1}", answer.id %>
  <% end %>
  <%= submit_tag "Reveal", id: 'submit-button', class: 'submit-button-style d-flex justify-content-center' %>
  <% end %>
</div>


</div>
<script>

  // Script to during the make the Body element grey
  let myBody = document.querySelector('body');
  const changeBodyBackgroundColor = () => {
    myBody.style.background = '#F8F9FA';
  }
  changeBodyBackgroundColor();

  // Script to get the current Sort
  const getCurrentSort = () => {
    let sorted = document.querySelectorAll(".sort-option")
    return sorted;
  }

  const bindGetSortToReveal = () => {
    let scoreButton = document.getElementById("submit-button")
    scoreButton.addEventListener("click", (event) => {
      // event.preventDefault()
      let answersOrdered = getCurrentSort();
      let i = 0
      answersOrdered.forEach((answer) => {
        let value = answer.dataset.answerNumber
        let formInput = document.querySelector(`input[name="answer_${i + 1}"]`)
        formInput.value = value
        i++
      })
      // DEBUG:
      // console.log('FORM INPUTS')
      // document.querySelectorAll('input[name*=answer]').forEach((input) => {
      //   console.log(input.value)
      // })
    })
  }
  bindGetSortToReveal()
</script>